# Generated by Django 5.1.3 on 2024-11-26 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.endereco'),
        ),
        migrations.RemoveField(
            model_name='tiposervico',
            name='servicos',
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='servicos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='backend.servico'),
        ),
    ]
