# Generated by Django 5.1.3 on 2024-11-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_cliente_endereco_remove_tiposervico_servicos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervico',
            name='servicos',
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.tiposervico'),
        ),
    ]
