# Generated by Django 5.1.3 on 2024-11-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_tiposervico_servicos_servico_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tiposervico'),
        ),
    ]
