GET http://localhost:8000/test_token 
Content-Type: application/json 
Authorization: Token 7c472700b07355d0bf54966cfd2b38b6328cb389

POST http://localhost:8000/api/signup
Content-Type: application/json

{
    "username": "neto",
    "password": "neto",
    "email": "neto@gmail.com",
    "cpf": "12345678945"
}

###


POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "neto",
    "password": "neto"
}




##

