# Generated by Django 5.1.4 on 2025-01-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='usuario',
            new_name='user',
        ),
    ]
