# Generated by Django 5.1.4 on 2025-01-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_aluno_cpf_alter_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
    ]
