# Generated by Django 5.1.4 on 2025-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_aluno_cpf_remove_aluno_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='user',
            new_name='usuario',
        ),
    ]
