# Generated by Django 5.1.4 on 2025-01-20 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_aluno_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
