# Generated by Django 5.1.4 on 2025-01-29 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_coordenador_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('alunos', models.ManyToManyField(blank=True, null=True, related_name='disciplinas', to='api.aluno')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='api.professor')),
            ],
        ),
    ]
